### ISSUE TITLE
gif file is too large

### ISSUE THREAD

**Issue by tiann** [aaron-elkins/capture-gif-issue#1]
the gif file generated is too large, i set the frame to 5ms and the frame delay to 200ms; record 5 second the file is 10M. it is almost useless on web, can you optimise this? 
consider use pngquant to compress the png file？

**Comment by orklann** [comment]
Thanks for feedback, and good call.

I will take a look at `pngquant` to see how good the compressed png files are, and finally decide if to use it to compress png files. Will update this issue after testing `pngquant`.

BTW, this feature will be available in next version 1.4.0 if possible. Because I think this is a good feature to reside in the 1.4.0 version number, not 1.3.14.

**Comment by tiann** [comment]
looking forward to your update！

**Comment by orklann** [comment]
@tiann
There is a bad news, I tried `pngquant` to compress PNGs before merging them into a GIF (Capture Gif used `whirlgif` command line internally to merge PNGs into one GIF file). `pngquant` perfectly compress PNGs to smaller size without losing quality, it's a cool utils. but after merging them into one GIFs, the wired thing happen, the resulting GIF was bigger than that without using `pngquant`, I pulled my hair out and was thinking it must be the issue of algorithm of `whirlgif`, so at present If you want to make smaller GIF file, I recommend you to set a smaller FPS before recording, I tested with a 3 fps and 5 seconds of recording, the resulting GIF file size is around 1.8MB. 

Or do you have any solution to reduce GIF size, but not to reduce the PNG size?

**Comment by tiann** [comment]
Sorry to hear that.

Maybe you can try [LZW algorithm](http://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art010). The [GIFLIB](http://sourceforge.net/projects/giflib/) contains some [implements](http://sourceforge.net/p/giflib/code/ci/5889d00ac21d92aeea3ded203dfa2b658210a277/tree/lib/dgif_lib.c#l740).

**Comment by orklann** [comment]
Need to close this issue, and the solution is to set a smaller FPS (3 - 5 fps) and you get still high quality GIF and smaller GIF file size.

Take a look at an example: [GIF sample](http://www.pixelegg.me/img/Vill%20Q/How%20To%20Install%20Vill%20Q.gif)
