### ISSUE TITLE
Settings to change border color when define screen area

### ISSUE THREAD

**Issue by deerawan** [aaron-elkins/capture-gif-issue#2]
Currently the default color is white. Sometimes it is hard to see it when the screen contain white color too. I hope it can be changed into another color which user can customize it.

**Comment by orklann** [comment]
Good idea.
Thanks for feedback.

Will pick a day to make this done.

**Comment by orklann** [comment]
Sorry, I am late.

This feature had been added in the newest update.

Need to close this issue
