### ISSUE TITLE
Recorded mouse location differs to actual on retina display

### ISSUE THREAD

**Issue by garethx** [aaron-elkins/capture-gif-issue#3]
![invitelink](https://cloud.githubusercontent.com/assets/1830035/14882833/aafc390c-0d32-11e6-8fd9-fa05e76bbbc2.gif)

**Comment by orklann** [comment]
@garethx 

Thank you for reporting this bug.

Does this bug just appear on retina display?

BTW, I can test on a retina display a while after, maybe 2 days later, cause the display is used by my farther.

I will try to reproduce this bug 2 days later.

**Comment by garethx** [comment]
I don't have access to a non-retina display to confirm behaviour on other types.

Ok, np.

**Comment by orklann** [comment]
@garethx 

I see, I should test on retina and non-retina display, but i guess this bug should be just available on retina display.

Sorry for the bug and will fix it soon.

**Comment by orklann** [comment]
Hi @garethx, I think I have fixed the bug, and just tested in my mac, can you help to double check if the bug fixed? 

Here is the link to download the new app

[Fixed Version of Capture Gif](https://www.dropbox.com/s/ezrgv9ifnoll1xc/Capture%20Gif%20-%20Bug%20Fixed%20version.app.zip?dl=1)

And many thanks.

**Comment by garethx** [comment]
Yep, that’s working for me! Thanks for the speedy fix.

On 1 May 2016 at 06:31:44, ryh (notifications@github.com) wrote:

Hi @garethx, I think I have fixed the bug, and just tested in my mac, can you help to double check if the bug fixed?

Here is the link to download the new app

Fixed Version of Capture Gif

And many thanks.

**Comment by orklann** [comment]
Great to hear that. Thanks for the bug report again. 
And yep, it's done.
