### ISSUE TITLE
HomeBrew support

### ISSUE THREAD

**Issue by yoavram** [aaron-elkins/capture-gif-issue#5]
Can you add support to install with HomeBrew, or at least provide MD5 of the dmg from the site?

**Comment by orklann** [comment]
Hi,

First of all, utilities in Homebrew are all open source, but Capture Gif is a commercial app, so it’s not suitable to add it to Homebrew,

But providing MD5 on the webpage is a good idea. I will add it to the webpage soon.

Best,
Aaron

**Comment by yoavram** [comment]
I think that cask is not limited to open source but I might be wrong: https://caskroom.github.io

**Comment by orklann** [comment]
It’s open source, https://github.com/caskroom/homebrew-cask <https://github.com/caskroom/homebrew-cask>

I am adding the md5 hash to the webpage...

**Comment by yoavram** [comment]
I'm not arguing - you do what you want with your app.
But I understand that cask allows to install apps that are not open source:
> providing a friendly Homebrew-style CLI workflow for the administration of macOS applications distributed as binaries.

(from the link you send). Of course cask itself is open source.

**Comment by orklann** [comment]
Anyway, thanks for your feedback.

Just finished adding MD5 hash of Capture Gif dmg to the webpage.
